export const DisplayData = [
  {
    date: {
      day: 19,
      month: 2,
      year: 2019,
    },
    countryCode: 'AUD',
    type: 'Stock Trade Commission',
    action: 'Action 1',
    amountAUD: -12.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 29,
      month: 11,
      year: 2018,
    },
    countryCode: 'AUD',
    type: 'Deposit',
    action: 'Action 2',
    amountAUD: -12.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 11,
      month: 1,
      year: 2017,
    },
    countryCode: 'AUD',
    type: 'Deposit 2',
    action: 'Action 3',
    amountAUD: -5.23,
    endingCashAUD: 4567.18,
  },
  {
    date: {
      day: 20,
      month: 12,
      year: 2015,
    },
    countryCode: 'AUD',
    type: 'Stock Trade Commission 2',
    action: 'Action 4',
    amountAUD: -12.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 31,
      month: 12,
      year: 2019,
    },
    countryCode: 'AUD',
    type: 'Deposit 2',
    action: 'Action 5',
    amountAUD: -12.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 5,
      month: 5,
      year: 2013,
    },
    countryCode: 'AUD',
    type: 'Deposit 3',
    action: 'Action 6',
    amountAUD: -5.23,
    endingCashAUD: 4567.18,
  },
  {
    date: {
      day: 15,
      month: 2,
      year: 2012,
    },
    countryCode: 'USD',
    type: 'Deposit USD 1',
    action: 'Action 4',
    amountAUD: -24.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 31,
      month: 12,
      year: 2011,
    },
    countryCode: 'USD',
    type: 'Deposit USD 3',
    action: 'Action USD 2',
    amountAUD: -2.91,
    endingCashAUD: 666746.18,
  },
  {
    date: {
      day: 19,
      month: 11,
      year: 2011,
    },
    countryCode: 'USD',
    type: 'Deposit USD 3',
    action: 'Action USD 2',
    amountAUD: -267.45,
    endingCashAUD: 4567121.18,
  },
];